-- QRyby — Community Restoration Engine
-- Stage 3: schema + RLS only. No wallet mutation, no live funding.
-- Lucjanek stays hidden in DRAFT until later stages explicitly activate it.

create table if not exists public.community_events (
  id uuid primary key default gen_random_uuid(),
  slug text not null unique,
  species_slug text not null,
  title text not null,
  target_qryb bigint not null check (target_qryb > 0),
  raised_qryb bigint not null default 0 check (raised_qryb >= 0 and raised_qryb <= target_qryb),
  donor_count integer not null default 0 check (donor_count >= 0),
  duration_seconds integer not null check (duration_seconds > 0),
  starts_at timestamptz,
  ends_at timestamptz,
  state text not null default 'draft'
    check (state in ('draft','funding','funded','failed','refunding','refunded','completed')),
  is_visible boolean not null default false,
  funded_at timestamptz,
  failed_at timestamptz,
  closed_at timestamptz,
  reward_type text not null,
  reward_count integer not null default 1 check (reward_count > 0),
  version bigint not null default 0 check (version >= 0),
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint community_events_time_window_chk
    check (
      (starts_at is null and ends_at is null)
      or
      (starts_at is not null and ends_at is not null and ends_at > starts_at)
    )
);

create table if not exists public.community_contributions (
  id bigint generated by default as identity primary key,
  event_id uuid not null references public.community_events(id) on delete restrict,
  user_id uuid not null references auth.users(id) on delete restrict,
  request_id uuid not null unique,
  amount_qryb bigint not null check (amount_qryb > 0),
  display_name text not null default 'ANONIM'
    check (char_length(display_name) between 1 and 32),
  is_anonymous boolean not null default false,
  created_at timestamptz not null default now(),
  refunded_at timestamptz,
  constraint community_contributions_refund_time_chk
    check (refunded_at is null or refunded_at >= created_at)
);

create table if not exists public.community_event_rewards (
  id uuid primary key default gen_random_uuid(),
  event_id uuid not null unique references public.community_events(id) on delete restrict,
  reward_type text not null,
  reward_count integer not null default 1 check (reward_count > 0),
  state text not null default 'locked'
    check (state in ('locked','pending','executing','executed','failed')),
  execution_key uuid not null unique default gen_random_uuid(),
  payload jsonb not null default '{}'::jsonb,
  attempt_count integer not null default 0 check (attempt_count >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  executed_at timestamptz
);

create index if not exists community_events_state_idx
  on public.community_events (state, is_visible);

create index if not exists community_contributions_event_created_idx
  on public.community_contributions (event_id, created_at desc);

create index if not exists community_contributions_user_created_idx
  on public.community_contributions (user_id, created_at desc);

create index if not exists community_contributions_event_user_idx
  on public.community_contributions (event_id, user_id);

create index if not exists community_event_rewards_state_idx
  on public.community_event_rewards (state);

create or replace function public.community_touch_updated_at()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists community_events_touch_updated_at on public.community_events;
create trigger community_events_touch_updated_at
before update on public.community_events
for each row execute function public.community_touch_updated_at();

drop trigger if exists community_event_rewards_touch_updated_at on public.community_event_rewards;
create trigger community_event_rewards_touch_updated_at
before update on public.community_event_rewards
for each row execute function public.community_touch_updated_at();

alter table public.community_events enable row level security;
alter table public.community_contributions enable row level security;
alter table public.community_event_rewards enable row level security;

drop policy if exists community_events_read_visible on public.community_events;
create policy community_events_read_visible
on public.community_events
for select
to authenticated
using (is_visible = true and state <> 'draft');

drop policy if exists community_contributions_read_visible_event on public.community_contributions;
create policy community_contributions_read_visible_event
on public.community_contributions
for select
to authenticated
using (
  exists (
    select 1
    from public.community_events e
    where e.id = community_contributions.event_id
      and e.is_visible = true
      and e.state <> 'draft'
  )
);

-- Rewards are deliberately server-only at Stage 3: RLS is enabled and
-- no anon/authenticated policy is created.

revoke all on table public.community_events from anon, authenticated;
revoke all on table public.community_contributions from anon, authenticated;
revoke all on table public.community_event_rewards from anon, authenticated;

grant select on table public.community_events to authenticated;
grant select on table public.community_contributions to authenticated;

insert into public.community_events (
  slug, species_slug, title, target_qryb, raised_qryb, donor_count,
  duration_seconds, starts_at, ends_at, state, is_visible,
  reward_type, reward_count, metadata
)
values (
  'lucjanek',
  'lucjanek',
  'IKRA LUCJANKA',
  500000000,
  0,
  0,
  604800,
  null,
  null,
  'draft',
  false,
  'EKO_RANDOM_SPAWNING_SCENARIO',
  1,
  '{"stage":3,"funding_live":false}'::jsonb
)
on conflict (slug) do nothing;

insert into public.community_event_rewards (
  event_id, reward_type, reward_count, state, payload
)
select
  e.id,
  e.reward_type,
  e.reward_count,
  'locked',
  '{"species_slug":"lucjanek"}'::jsonb
from public.community_events e
where e.slug = 'lucjanek'
on conflict (event_id) do nothing;
