plugins {
    id 'com.android.application'
}

android {
    namespace 'com.architektkariery.qryby'
    compileSdk 35

    defaultConfig {
        applicationId 'com.architektkariery.qryby.beta012'
        minSdk 26
        targetSdk 35
        versionCode 3
        versionName '0.1.2'
    }

    buildTypes {
        debug {
            applicationIdSuffix ''
            versionNameSuffix '-beta'
        }
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
}

